-- =====================================================================
-- Fix BoatOptions Table Schemas (2015-2025)
-- =====================================================================
-- Adds missing CPQ columns to BoatOptions15 through BoatOptions25
-- to match the schema of BoatOptions26
--
-- Missing columns:
--   - ConfigID: Configuration ID for CPQ orders
--   - ValueText: Configuration attribute value text
--   - C_Series: Series code from CPQ
--   - order_date: Order date
--   - external_confirmation_ref: External confirmation reference
--   - MSRP: Manufacturer's Suggested Retail Price
--   - CfgName: Configuration attribute name
--   - CfgPage: Configuration page
--   - CfgScreen: Configuration screen
--   - CfgValue: Configuration value
--   - CfgAttrType: Configuration attribute type
--
-- Author: Claude Code
-- Date: 2026-02-09
-- =====================================================================

USE warrantyparts;

-- BoatOptions15 (2015)
ALTER TABLE BoatOptions15
    ADD COLUMN ConfigID VARCHAR(30) DEFAULT NULL,
    ADD COLUMN ValueText VARCHAR(100) DEFAULT NULL,
    ADD COLUMN C_Series VARCHAR(50) DEFAULT NULL,
    ADD COLUMN order_date DATE DEFAULT NULL,
    ADD COLUMN external_confirmation_ref VARCHAR(30) DEFAULT NULL,
    ADD COLUMN MSRP DECIMAL(10,2) DEFAULT NULL,
    ADD COLUMN CfgName VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgPage VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgScreen VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgValue VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgAttrType VARCHAR(20) DEFAULT NULL;

-- BoatOptions16 (2016)
ALTER TABLE BoatOptions16
    ADD COLUMN ConfigID VARCHAR(30) DEFAULT NULL,
    ADD COLUMN ValueText VARCHAR(100) DEFAULT NULL,
    ADD COLUMN C_Series VARCHAR(50) DEFAULT NULL,
    ADD COLUMN order_date DATE DEFAULT NULL,
    ADD COLUMN external_confirmation_ref VARCHAR(30) DEFAULT NULL,
    ADD COLUMN MSRP DECIMAL(10,2) DEFAULT NULL,
    ADD COLUMN CfgName VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgPage VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgScreen VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgValue VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgAttrType VARCHAR(20) DEFAULT NULL;

-- BoatOptions17 (2017)
ALTER TABLE BoatOptions17
    ADD COLUMN ConfigID VARCHAR(30) DEFAULT NULL,
    ADD COLUMN ValueText VARCHAR(100) DEFAULT NULL,
    ADD COLUMN C_Series VARCHAR(50) DEFAULT NULL,
    ADD COLUMN order_date DATE DEFAULT NULL,
    ADD COLUMN external_confirmation_ref VARCHAR(30) DEFAULT NULL,
    ADD COLUMN MSRP DECIMAL(10,2) DEFAULT NULL,
    ADD COLUMN CfgName VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgPage VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgScreen VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgValue VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgAttrType VARCHAR(20) DEFAULT NULL;

-- BoatOptions18 (2018)
ALTER TABLE BoatOptions18
    ADD COLUMN ConfigID VARCHAR(30) DEFAULT NULL,
    ADD COLUMN ValueText VARCHAR(100) DEFAULT NULL,
    ADD COLUMN C_Series VARCHAR(50) DEFAULT NULL,
    ADD COLUMN order_date DATE DEFAULT NULL,
    ADD COLUMN external_confirmation_ref VARCHAR(30) DEFAULT NULL,
    ADD COLUMN MSRP DECIMAL(10,2) DEFAULT NULL,
    ADD COLUMN CfgName VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgPage VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgScreen VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgValue VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgAttrType VARCHAR(20) DEFAULT NULL;

-- BoatOptions19 (2019)
ALTER TABLE BoatOptions19
    ADD COLUMN ConfigID VARCHAR(30) DEFAULT NULL,
    ADD COLUMN ValueText VARCHAR(100) DEFAULT NULL,
    ADD COLUMN C_Series VARCHAR(50) DEFAULT NULL,
    ADD COLUMN order_date DATE DEFAULT NULL,
    ADD COLUMN external_confirmation_ref VARCHAR(30) DEFAULT NULL,
    ADD COLUMN MSRP DECIMAL(10,2) DEFAULT NULL,
    ADD COLUMN CfgName VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgPage VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgScreen VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgValue VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgAttrType VARCHAR(20) DEFAULT NULL;

-- BoatOptions20 (2020)
ALTER TABLE BoatOptions20
    ADD COLUMN ConfigID VARCHAR(30) DEFAULT NULL,
    ADD COLUMN ValueText VARCHAR(100) DEFAULT NULL,
    ADD COLUMN C_Series VARCHAR(50) DEFAULT NULL,
    ADD COLUMN order_date DATE DEFAULT NULL,
    ADD COLUMN external_confirmation_ref VARCHAR(30) DEFAULT NULL,
    ADD COLUMN MSRP DECIMAL(10,2) DEFAULT NULL,
    ADD COLUMN CfgName VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgPage VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgScreen VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgValue VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgAttrType VARCHAR(20) DEFAULT NULL;

-- BoatOptions21 (2021)
ALTER TABLE BoatOptions21
    ADD COLUMN ConfigID VARCHAR(30) DEFAULT NULL,
    ADD COLUMN ValueText VARCHAR(100) DEFAULT NULL,
    ADD COLUMN C_Series VARCHAR(50) DEFAULT NULL,
    ADD COLUMN order_date DATE DEFAULT NULL,
    ADD COLUMN external_confirmation_ref VARCHAR(30) DEFAULT NULL,
    ADD COLUMN MSRP DECIMAL(10,2) DEFAULT NULL,
    ADD COLUMN CfgName VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgPage VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgScreen VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgValue VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgAttrType VARCHAR(20) DEFAULT NULL;

-- BoatOptions22 (2022)
ALTER TABLE BoatOptions22
    ADD COLUMN ConfigID VARCHAR(30) DEFAULT NULL,
    ADD COLUMN ValueText VARCHAR(100) DEFAULT NULL,
    ADD COLUMN C_Series VARCHAR(50) DEFAULT NULL,
    ADD COLUMN order_date DATE DEFAULT NULL,
    ADD COLUMN external_confirmation_ref VARCHAR(30) DEFAULT NULL,
    ADD COLUMN MSRP DECIMAL(10,2) DEFAULT NULL,
    ADD COLUMN CfgName VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgPage VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgScreen VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgValue VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgAttrType VARCHAR(20) DEFAULT NULL;

-- BoatOptions23 (2023)
ALTER TABLE BoatOptions23
    ADD COLUMN ConfigID VARCHAR(30) DEFAULT NULL,
    ADD COLUMN ValueText VARCHAR(100) DEFAULT NULL,
    ADD COLUMN C_Series VARCHAR(50) DEFAULT NULL,
    ADD COLUMN order_date DATE DEFAULT NULL,
    ADD COLUMN external_confirmation_ref VARCHAR(30) DEFAULT NULL,
    ADD COLUMN MSRP DECIMAL(10,2) DEFAULT NULL,
    ADD COLUMN CfgName VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgPage VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgScreen VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgValue VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgAttrType VARCHAR(20) DEFAULT NULL;

-- BoatOptions24 (2024)
ALTER TABLE BoatOptions24
    ADD COLUMN ConfigID VARCHAR(30) DEFAULT NULL,
    ADD COLUMN ValueText VARCHAR(100) DEFAULT NULL,
    ADD COLUMN C_Series VARCHAR(50) DEFAULT NULL,
    ADD COLUMN order_date DATE DEFAULT NULL,
    ADD COLUMN external_confirmation_ref VARCHAR(30) DEFAULT NULL,
    ADD COLUMN MSRP DECIMAL(10,2) DEFAULT NULL,
    ADD COLUMN CfgName VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgPage VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgScreen VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgValue VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgAttrType VARCHAR(20) DEFAULT NULL;

-- BoatOptions25 (2025)
ALTER TABLE BoatOptions25
    ADD COLUMN ConfigID VARCHAR(30) DEFAULT NULL,
    ADD COLUMN ValueText VARCHAR(100) DEFAULT NULL,
    ADD COLUMN C_Series VARCHAR(50) DEFAULT NULL,
    ADD COLUMN order_date DATE DEFAULT NULL,
    ADD COLUMN external_confirmation_ref VARCHAR(30) DEFAULT NULL,
    ADD COLUMN MSRP DECIMAL(10,2) DEFAULT NULL,
    ADD COLUMN CfgName VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgPage VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgScreen VARCHAR(50) DEFAULT NULL,
    ADD COLUMN CfgValue VARCHAR(100) DEFAULT NULL,
    ADD COLUMN CfgAttrType VARCHAR(20) DEFAULT NULL;

-- Verification query to check all tables now have 31 columns
SELECT
    TABLE_NAME,
    COUNT(*) as column_count
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'warrantyparts'
  AND TABLE_NAME REGEXP '^BoatOptions[0-9]{2}$'
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;
