insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','CMP-ADHTAP','ADHESIVES & TAPES');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','CMP-BADGE','BADGING & GRAPHICS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','CMP-CLOSUR','CLOSURES');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','CMP-CNCALU','ALUMINUM-MILLED/TURNED/ASSEMBLED');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','CMP-FASTNR','FASTENERS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','CMP-GSKTSL','GASKETS & SEALS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','CMP-STNLS','STAINLESS STEEL-WELDED/CAST/FORMED');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','CMP-WOOD','WOOD & COMPOSITE');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','EXT-ARCHES','ARCHES');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','EXT-BIMINI','BIMINI');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','EXT-COATNG','COATINGS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','EXT-COVER','COVERS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','EXT-FBRGLS','FIBERGLASS CONSOLES');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','EXT-LADDER','LADDERS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','EXT-PNTRLS','PAINTED RAILS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','EXT-RAWALM','RAW ALUMINUM - NORTH & WEST');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','EXT-WNDSHD','GLASS WINDSHIELDS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','INT-FLRING','FLOORING & MATS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','INT-FURN','FURNITURE ASSEMBLIES');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','INT-PLASTC','FUNCTIONAL PLASTICS-MOLD/FORM/CNC');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','INT-STRWHL','STEERING WHEELS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','INT-WRAP','WRAPPED SHROUDS-VACUUM/STITCH/FOAM');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','NPC-PRDSUP','PRODUCTION SUPPLIES');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','RES-AUDIO','AUDIO SYSTEMS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','RES-ENGRIG','ENGINE RIGGING');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','RES-GAUGE','GAUGING, SWITCHING, MODULES & SENS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','RES-LIGHT','LIGHTING SYSTEMS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','RES-PWRDST','ELECTRICAL DISTRIBUTION SYSTEMS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','RES-REGULA','REGULATORY');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','RES-STEER','STEERING SYSTEMS');
insert into famcode_mst (site_ref,family_code,[description]) VALUES('BENN','RES-TANKS','BOAT SYSTEMS-FUEL/WATER/AIR/ANCHOR');
